on:
  push:
    branches-ignore:
    - master

name: CI
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        name: Build and push
        uses: actions/testaction@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.testaction }}
      -
        name: Build and push to docker
        uses: hdmares/dock4321@v1
        with:
          push: false
          tag_with_reg : true
          tag_with_sha : true
          tags: ${{ github.sha }}